export const GET_PRODUCTS = 'GET_PRODUCTS'
export const CREATE_PRODUCT = 'CREATE_PRODUCT'

export const GET_ORDERS = 'GET_ORDERS'
export const UPDATE_ORDER = 'UPDATE_ORDER'
export const REMOVE_ORDERS = 'REMOVE_ORDERS'

// export const GET_ALL_REVIEWS = 'GET_ALL_REVIEWS'
export const CREATE_REVIEW = 'CREATE_REVIEW'
export const DELETE_REVIEW = 'DELETE_REVIEW'
export const GET_PRODUCT_REVIEWS = 'GET_PRODUCT_REVIEWS'
export const EDIT_REVIEW = 'EDIT_REVIEW'

export const SET_AUTH = 'SET_AUTH'
export const LOGOUT = 'LOGOUT'


export const GET_CATEGORIES = 'GET_CATEGORIES'

