
    Product.create({
      name: 'A Paperclip Cang Found',
      imageUrl: '/images/No_image_available.png',
      price: 100,
      stock: 200,
      description: 'description placeholder',
    }),
    Product.create({
      name: 'Lint from Zi\'s Left Pocket',
      imageUrl: '/images/No_image_available.png',
      price: 100,
      stock: 200,
      description: 'description placeholder',
    }),
    Product.create({
      name: 'A Paperclip Cang Found',
      imageUrl: '/images/No_image_available.png',
      price: 100,
      stock: 200,
      description: 'description placeholder',
    }),
    Product.create({
      name: 'A Paperclip Cang Found',
      imageUrl: '/images/No_image_available.png',
      price: 100,
      stock: 200,
      description: 'description placeholder',
    }),
    Product.create({
      name: 'A Paperclip Cang Found',
      imageUrl: '/images/No_image_available.png',
      price: 100,
      stock: 200,
      description: 'description placeholder',
    }),
    Product.create({
      name: 'A Paperclip Cang Found',
      imageUrl: '/images/No_image_available.png',
      price: 100,
      stock: 200,
      description: 'description placeholder',
    }),
    Product.create({
      name: 'A Paperclip Cang Found',
      imageUrl: '/images/No_image_available.png',
      price: 100,
      stock: 200,
      description: 'description placeholder',
    })