
    Product.create({
      name: 'A Paperclip Cang Found',
      imageUrl: 'https://d29mh04qrg9hzh.cloudfront.net/bmxbike_small.jpg',
      price: 100,
      stock: 200,
      description: 'description placeholder',
    }),
    Product.create({
      name: 'Lint from Zi\'s Left Pocket',
      imageUrl: 'https://d29mh04qrg9hzh.cloudfront.net/bmxbike_small.jpg',
      price: 100,
      stock: 200,
      description: 'description placeholder',
    }),
    Product.create({
      name: 'A Paperclip Cang Found',
      imageUrl: 'https://d29mh04qrg9hzh.cloudfront.net/bmxbike_small.jpg',
      price: 100,
      stock: 200,
      description: 'description placeholder',
    }),
    Product.create({
      name: 'A Paperclip Cang Found',
      imageUrl: 'https://d29mh04qrg9hzh.cloudfront.net/bmxbike_small.jpg',
      price: 100,
      stock: 200,
      description: 'description placeholder',
    }),
    Product.create({
      name: 'A Paperclip Cang Found',
      imageUrl: 'https://d29mh04qrg9hzh.cloudfront.net/bmxbike_small.jpg',
      price: 100,
      stock: 200,
      description: 'description placeholder',
    }),
    Product.create({
      name: 'A Paperclip Cang Found',
      imageUrl: 'https://d29mh04qrg9hzh.cloudfront.net/bmxbike_small.jpg',
      price: 100,
      stock: 200,
      description: 'description placeholder',
    }),
    Product.create({
      name: 'A Paperclip Cang Found',
      imageUrl: 'https://d29mh04qrg9hzh.cloudfront.net/bmxbike_small.jpg',
      price: 100,
      stock: 200,
      description: 'description placeholder',
    })